### ISSUE TITLE
compiling problem 

### ISSUE THREAD

**Issue by JakobHeller** [JakobHeller/NatureInspiredComputing#1]
g++ -std=c++11 -c Khexplorer.cpp #compiler option: '-std=c++11' for older gcc version
Khexplorer.cpp: In function ‘int main()’:
Khexplorer.cpp:12:5: error: ‘CController’ was not declared in this scope
     CController control(&util); //not declared in this scope
     ^
Khexplorer.cpp:14:5: error: ‘COperator’ was not declared in this scope
     COperator operate(&util); //not declared in this scope
     ^
Khexplorer.cpp:17:2: error: ‘control’ was not declared in this scope
  control.Start();
  ^
Khexplorer.cpp:19:2: error: ‘operate’ was not declared in this scope
  operate.Start();
  ^
Makefile:5: recipe for target 'Khexplorer.o' failed
make: *** [Khexplorer.o] Error 1

**Comment by JNLossner** [comment]
Error was a misplaced #else in almost all header files.
