### ISSUE TITLE
Warte Befehl einfügen

### ISSUE THREAD

**Issue by JakobHeller** [JakobHeller/NatureInspiredComputing#2]

**Comment by JNLossner** [comment]
Man könnte Tastaturanschläge (im main()?) auffangen und dementsprechend Befehle umsetzen, z.b.

- ESC : Roboter stoppen und Programm beenden.
- SPACE (laufend): Controller ausschalten und Roboter stoppen.
- SPACE (gestoppt): Controller einschalten (Roboter fährt los).

**Comment by JNLossner** [comment]
Konsolenbefehle funktionieren. Auszug aus der Hilfe:

   help : lists this help
   exit : ends the program
   go : starts the robot
   stop : stops the robot
   smart : enables robot learning
   stupid : disables robot learning
