### ISSUE TITLE
variables einfügen von Stützstellen

### ISSUE THREAD

**Issue by JakobHeller** [JakobHeller/NatureInspiredComputing#3]
-wann werden neue Stützstellen eingefügt, wann entfernt
-wo werden die eingefügt? ist das adaptiv?

**Comment by JNLossner** [comment]
Idee zum Einfügen der Stützstellen:

1. Sensordaten werden im Controller wie gehabt durch das Netzwerk geschickt.
2. Ist die Gesamtaktivierung zu niedrig, wird die Stützstelle mit den errechneten Gewichten hinzugefügt.
2.a. Optional wird ein zufälliger Wert hinzugefügt.
3. Das ValueSystem überprüft das Ergebnis und gibt wie gehabt seine Wunschgeschwindigkeit aus.
4. Der Controller ruft, nachdem er seine neue Stützstelle eingefügt hat, den Korrekturwunsch ab und passt ganz normal die Gewichte der Stützstellen (inklusive der neuen Stelle) an.

Idee zum Entfernen:
1. Nodes werden mit einem "Nutzwert" versehen.
2. Dieser "Nutzwert" klingt mit jedem Zyklus ab.
3. Wird der Node aktiviert, wird der Aktivierungsgrad dem Nutzwert hinzuaddiert, sodass er kurzzeitig steig.
4. Ist der Nutzwert zu niedrig geworden (relativ zu allen Nutzwerten?), wird die Stützstelle entfernt.

Erhofftes Gesamtergebnis:
- Der Roboter kultiviert die häufigsten Stützstellen und reagiert dementsprechend dort am stabilsten
- Geht ihm ein Sensor verloren, werden mit der Zeit die Stützstellen auf seine neue Lebenssituation angepasst.

Was denkst du? Könnte das klappen? An sich wäre es leicht zu implementieren.

**Comment by JNLossner** [comment]
Das hinzufügen und "vergessen" von Stützstellen ist implementiert. Eventuell müsste eine Anpassung des "Sigma" Wertes mit eingearbeitet werden, um die Stützstellendichte in den relevanten Bereichen zu erhöhen.

**Comment by JNLossner** [comment]
Funktioniert. Sigma-Anpassung ist ein Problem für sich.
