### ISSUE TITLE
Speichern / Laden von Stützstellen

### ISSUE THREAD

**Issue by JNLossner** [JakobHeller/NatureInspiredComputing#7]
- Im CController die SNodes aus einer Datei laden
- Im CController die SNodes in eine Datei speichern
- Khexplorer.cpp: Kommandos samt Pfad hinzufügen, eventuell mit "Unterfunktion" um mehrere Argumente zu nehmen

**Comment by JakobHeller** [comment]
Khep kann jetzt speichern und laden, aber erst mal nur in einen vorgefertigten Pfad. Ein untermenü würde aber Sinn machen denke ich, weil wir dann schneller verscheidene Versionen Laden könnten.

Ein anderer Gedanke der mir beim bauen gekommen ist; Bisher löscht LoadfromFile alle bestehenden Nodes, er könnte sie aber auch super easy einfahc hinzufügen. (er würde dann entweder ergänzen oder alte knoten herausdrängen) Da war ich mir aber nicht sicher, ob das in allen Anwendungen wirklich sinnvoll ist. Können wir ja am Dienstag mal diskutieren.

**Comment by JNLossner** [comment]
Ganz ganz wichtig: Sigma anpassen an die Node-Abstände!

**Comment by JNLossner** [comment]
Speichern und Laden ist ausgiebig getestet und funktioniert.
