### ISSUE TITLE
Virtuelle Sensoren / Outputs

### ISSUE THREAD

**Issue by JNLossner** [JakobHeller/NatureInspiredComputing#9]
Prinzipiell sollten wir vielleicht versuchen, die Dimensionen unseres Problems zu reduzieren. Zusätzlich ist es eigentlich nicht sinnvoll, LINKS und RECHTS im RBF getrennt zu behandeln; von daher mein Vorschlag:

- Die realen Sensoren in virtuelle Sensoren konvertieren, die möglicherweise andere Abdeckungen oder Spannen haben (weniger Punkte in den Dimensionen).
- Als Ausgabe nicht mehr links/rechts, sondern einen Winkel, in dem wir uns drehen wollen (ähnlich wie zur Zeit im ValueSystem hinterlegt). Dieser wird mit dann vom Operator mit der aktuellen Geschwindigkeit verrechnet.
- Die aktuelle Geschwindigkeit kann tatsächlich dadurch unabhängig steigen, wenn eine Zeit lang keine Bumps vorkamen.

Was hältst du von der Idee?

**Comment by JNLossner** [comment]
Wo wir schon dabei sind - da das Rauschen sowieso riesig ist, könnten wir die Werte relativ stark quantisieren. Beispielsweise:

Sensoren-Entfernungsstufen:
0. Proximity_Clear (<500)
1. Proximity_Near (<800)
2. Proximity_Close (<1000)
3. Proximity_Collision

Fahrtwinkel könnten auch quantisiert werden... (90°, 45°, 0°, -45°, -90°)
Denn letztendlich sind sie ja keine absoluten Drehwinkel, sondern geben an wie hoch der drehende bzw. geradeaus fahrende Anteil ist.

**Comment by JakobHeller** [comment]
Das Problem beim Quantisieren der Sensoren ist glaube ich die größe der "steps". Ich glaube solche Stufen sollten höchsten so groß sein, wie peak to peak vom durschnittlichen rausche. Das wäre in unserem Fall 60. 
Die Quantisierung der Fahrtwinkel finde ich prinzipiell auch eine sehr gute Idee, aber ich glaube, dass es schwierig wird z.b an einer Wand entlang zu fahren. Da bräuchte man vielleicht auch kleinere Abstufungen! Ich finde das mit den Drehwinkeln auch generell noch nicht so gelungen, weil die Winkel wo hin er sich dreht ja eigentlich sehr stark von der Geschwindigkeit abhängen (?) und wir noch nicht getestet haben, ob das ungefähr hinkommt wie weit er sich da dreht.

Das mit links und rechts trennen habe ich noch nicht so voll und ganz verstanden. Du willst also quasi sagen fahr 30° und er bildet sich dann abhängig von seiner Geschwindigkeit daraus die beiden Doubles für die beiden Motoren?
